### PR TITLE
Added Guide On How To Get "Pair Extraordinaire" Badge

### LINKED ISSUE #3: so how would we get Pair Extraordinaire

### PR DESCRIPTION
**Pull request by ArnavK-09**

### CODE REVIEW

**Comment by ArnavK-09** [comment]
@dimmasyusuf 🗿

**Comment by ArnavK-09** [comment]
@dimmasyusuf ?

**Comment by ArnavK-09** [comment]
@dimmasyusuf hey

**Comment by ArnavK-09** [comment]
@dimmasyusuf dead?

**Comment by ArnavK-09** [comment]
@dimmasyusuf bruh

**Comment by ArnavK-09** [comment]
@dimmasyusuf

**Comment by ArnavK-09** [comment]
@dimmasyusuf

**Comment by ArnavK-09** [comment]
@dimmasyusuf bryha

**Comment by ArnavK-09** [comment]
@dimmasyusuf

**Review by dimmasyusuf — APPROVED** [review]
thanks for contributing into my repo, i just got back into coding, sorry for waiting

**Pull request merged**
